version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: finplan-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./financial_planning.db
      - SECRET_KEY=your-secret-key-change-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./backend:/app
      - backend-data:/app/data
    networks:
      - finplan-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: finplan-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - finplan-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: PostgreSQL for production
  postgres:
    image: postgres:15-alpine
    container_name: finplan-db
    environment:
      - POSTGRES_DB=finplan
      - POSTGRES_USER=finplan
      - POSTGRES_PASSWORD=changeme
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - finplan-network
    restart: unless-stopped
    profiles:
      - production

networks:
  finplan-network:
    driver: bridge

volumes:
  backend-data:
  postgres-data: